name: "Build"

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install OSS-Cad-Suite
        uses: YosysHQ/setup-oss-cad-suite@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: docker run --rm -v $(pwd):/work -v /home/runner/work/_temp/oss-cad-suite:/tabby yosyshq/plugin_build_x64:22.04 make

      - name: Install
        run: |
          cp /home/runner/work/_temp/oss-cad-suite/bin/eqy .
          make install PREFIX=/home/runner/work/_temp/oss-cad-suite
          cp -f /home/runner/work/_temp/oss-cad-suite/bin/eqy /home/runner/work/_temp/oss-cad-suite/libexec/.
          cp -f eqy /home/runner/work/_temp/oss-cad-suite/bin/.

      - name: Test
        run: make test
