name: "Build"

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Install deps
        run: sudo apt-get install bison flex libreadline-dev tcl-dev libffi-dev

      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Install OSS-Cad-Suite
        uses: YosysHQ/setup-oss-cad-suite@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: make

      - name: Test
        run: make test
